### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by lasalvavida** [KhronosGroup/COLLADA2GLTF#71]
### 2.0
* [x] Backport 1.0 support #69
* [x] Merge #37 to master, park current master onto a 1.0 branch
* Ongoing response to 2.0 bug reports

### 1.0
* Respond to questions or converter issues
* Third-party pull requests for issues are welcome, but unless the issue is one of security, we should be focused more on #69 than trying to fix the old converter

### Misc
* [ ] Add OS X build to Travis CI #72 
* [ ] Proper C++11 detection #55 
* [ ] Improve CI build speed ~#54~ #75
* [ ] asm.js support #58 
* [ ] Memory leaks #70
* [ ] Texture conversion #73

**Comment by jeremyabel** [comment]
Would you be up for opening something in the Projects tab to track this? It's got a nice kanban board interface that makes it really easy to track todo lists and such.

**Comment by nitrologic** [comment]
I was recently confused that master is 1.0, is this correct? When will 2.0 be master? 

What is status of 1.0 considering 2.0 branch may not have feature to output 1.0 spec.

**Comment by lasalvavida** [comment]
Closing this roadmap issue in favor of using the GitHub projects tab.
